# Generated by Django 3.2.15 on 2022-08-04 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('like_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('follow_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('unfollow_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('comment_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('dm_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagram.client')),
            ],
        ),
    ]
