# Generated by Django 3.2.15 on 2022-08-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_auto_20220804_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
