# Generated by Django 3.2.15 on 2022-08-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_session_is_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='is_complete',
        ),
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('Running', 'Running'), ('Not Started', 'Not Started'), ('Finished', 'Finished'), ('Error', 'Error')], default='Not Started', max_length=255),
        ),
    ]
