# Generated by Django 3.2.15 on 2022-08-10 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0006_sessionlimit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionlimit',
            name='limits',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instagram.session'),
        ),
    ]
