# Generated by Django 3.2.15 on 2022-08-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0007_alter_sessionlimit_limits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionlimit',
            name='comment_count',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sessionlimit',
            name='dm_count',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sessionlimit',
            name='follow_count',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sessionlimit',
            name='like_count',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sessionlimit',
            name='unfollow_count',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
