# Generated by Django 3.2.15 on 2022-08-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0011_alter_sessionlimit_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='ff_ratio',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('Running', 'Running'), ('Not Started', 'Not Started'), ('Finished', 'Finished'), ('Error', 'Error'), ('Cancelled', 'Cancelled'), ('Sleeping', 'Sleeping')], default='Not Started', max_length=255),
        ),
    ]
