# Generated by Django 3.2.15 on 2022-08-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0013_session_last_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='ff_ratio',
        ),
        migrations.AddField(
            model_name='client',
            name='followers',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='following',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='ig_uid',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
