# Generated by Django 3.2.15 on 2022-08-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0014_auto_20220819_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ig_uid',
            field=models.PositiveBigIntegerField(blank=True, default=None, null=True),
        ),
    ]
