# Generated by Django 3.2.15 on 2022-08-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0015_alter_client_ig_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('Like Follow', 'Like Follow')], default='Like Follow', max_length=255),
        ),
    ]
