# Generated by Django 3.2.15 on 2022-08-23 10:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0016_alter_session_session_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('following', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('followers', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('ig_uid', models.PositiveBigIntegerField(blank=True, default=None, null=True)),
                ('last_finished', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='session',
            name='client',
        ),
        migrations.RemoveField(
            model_name='session',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='session',
            name='last_finished',
        ),
        migrations.RemoveField(
            model_name='session',
            name='start_time',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.AddField(
            model_name='session',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagram.bot'),
            preserve_default=False,
        ),
    ]
