# Generated by Django 3.2.15 on 2022-08-23 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0018_auto_20220823_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
