# Generated by Django 3.2.15 on 2022-08-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0019_auto_20220823_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='last_timeout',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='timeout_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
