# Generated by Django 3.2.15 on 2022-09-08 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0020_auto_20220824_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='last_timeout',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='timeout_until',
        ),
        migrations.AlterField(
            model_name='bot',
            name='status',
            field=models.CharField(choices=[('Following', 'Following'), ('Unfollowing', 'Unfollowing'), ('Idle', 'Idle')], default='Idle', max_length=255),
        ),
        migrations.AlterField(
            model_name='session',
            name='bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='instagram.bot'),
        ),
    ]
