# Generated by Django 3.2.15 on 2022-09-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0021_auto_20220908_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionlimit',
            name='relogin_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
