# Generated by Django 3.2.15 on 2022-09-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0022_sessionlimit_relogin_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSwitchInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_limit', models.PositiveSmallIntegerField(default=0)),
                ('higher_limit', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
